["exp"]
data_dir='data/'
model_dir='model/'
result_dir='result/'

["tree"]
data_dir='data/'
model_dir='model/tree/'
result_dir='result/tree/'

["real"]
data_dir='data/'
model_dir='model/real/'
result_dir='result/real/'

["gaussian"]
data_dir='data/'
model_dir='model/gaussian/'
result_dir='result/gaussian/'
